[features]
seeds = false
skip-lint = false

[programs.localnet]
aegis = "E9eCCUEZ5g41ddKGN9Coju43QzKJuEG4FEm32j1sTwNG"
fee_distributor = "7mLJQemwoCQztdtRXshEY7poKNKJN98m39foqvK3DnCg"
staking = "Dcrq8mcCkPVSRBc41hx9ZyDmbzbz2uT5rMLuaQrnqCE5"

[programs.devnet]
aegis = "E9eCCUEZ5g41ddKGN9Coju43QzKJuEG4FEm32j1sTwNG"
fee_distributor = "7mLJQemwoCQztdtRXshEY7poKNKJN98m39foqvK3DnCg"
staking = "Dcrq8mcCkPVSRBc41hx9ZyDmbzbz2uT5rMLuaQrnqCE5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vscode/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
